CREATE TABLE CUSTOMER (
	cid			INT PRIMARY KEY
	,cFname VARCHAR(100) NOT NULL
	,cLname VARCHAR(100) NOT NULL
);

CREATE TABLE SALESREP (
	repID		INT PRIMARY KEY
	,rFname VARCHAR(100) NOT NULL
	,rLname VARCHAR(100) NOT NULL
	,invoiceNBR INT FOREIGN KEY REFERENCES CUSTOMER(invID)

);

CREATE TABLE INVOICE (
	invID		INT		PRIMARY KEY
	, invDate	DATE	NOT NULL
	, totalAmt	DECIMAL(12,2)
	, cid		INT		FOREIGN KEY REFERENCES CUSTOMER(cid) NOT NULL

);

CREATE TABLE SECACCESS(
	secAccessID INT			PRIMARY KEY
	, userName VARCHAR(100) NOT NULL
	, lastLogin DATE
	, cid		INT			FOREIGN KEY REFERENCES CUSTOMER (cid) NOT NULL

);

