--step 1
SELECT *
FROM PRODUCTS
WHERE CITY = 'DALLAS'
	and PRICE = 1.00;

--step 2
SELECT *
FROM PRODUCTS
WHERE QUANTITY < 125000;

--step 3
SELECT *
FROM ORDERS
WHERE O_MONTH IN ('MARCH', 'APRIL', 'MAY');

--step 4
SELECT *
FROM CUSTOMERS
WHERE CNAME LIKE 'A%'; 

--step 5
SELECT *
FROM CUSTOMERS
WHERE DISCNT BETWEEN 7 and 9;