-- step 1
SELECT CUSTOMERS.CID, CUSTOMERS.CNAME, ORDERS.ORDNO, ORDERS.QTY
FROM CUSTOMERS JOIN ORDERS ON CUSTOMERS.CID = ORDERS.CID
ORDER BY CUSTOMERS.CID ASC;

-- step 2
SELECT CUSTOMERS.CID, CUSTOMERS.CNAME, ORDERS.ORDNO, ORDERS.QTY
FROM CUSTOMERS LEFT OUTER JOIN ORDERS ON CUSTOMERS.CID = ORDERS.CID
ORDER BY CUSTOMERS.CID ASC; 

-- step 3
SELECT O.ORDNO, O.QTY, C.CID, C.CNAME
FROM ORDERS O RIGHT OUTER JOIN CUSTOMERS C ON O.CID = C.CID
ORDER BY O.ORDNO ASC

