-- CREATE TABLE DDL FOR CUSTOMER (PK, no FK)
-- CREATE TABLE DDL FOR INVOICE (PK, no FK)

DROP TABLE INV2;

--BUILD AND ALTER
CREATE TABLE INV2 (
	invNBR INT PRIMARY KEY
	, custNBR INT --- will be FK
	, invDate DATE Not Null
); 
ALTER TABLE INV2
ADD CONSTRAINT FK_CUSTOMER FOREIGN KEY (custNBR)
	REFERENCES CUSTOMER(CUS_CODE);

-- CREATE FK WHEN BUILDING TABLE
-- INLINE DECLARATION 
CREATE TABLE INV2 (
	invNBR INT PRIMARY KEY
	, custNBR INT FOREIGN KEY REFERENCES CUSTOMER (CUS_CODE)
	, invDate DATE Not Null
); 


